### ISSUE TITLE
Create study-lock.yml

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#606]
Drivers: 

- `study.yml` should be unmodified by JabRef
- The SLR should be reproducible

Introduce `study-lock.yml` (similar to `package-lock.json`), where the really sent queries are contained. The -lock is a "superset" of the .yml file.

`study.yml`:

```
queries:
- query: JabRef AND Java
  - ACM Portal: "def"
  - IEEExplore: "abc"
```

`study-lock.yml`:

```yaml
queries:
- query: JabRef AND Java
  - ACM Portal: "def"
  - IEEExplore: "abc"
  - GVK"abc"
```
